### PR TITLE
added example

### PR DESCRIPTION
**Pull request by moebiussurfing**
dont' know if its important but i commented the line: if(std::isprint(static_cast<char>(key))) {

### CODE REVIEW

**Comment by 2bbb** [comment]
thanks for PR.
example is feeling good, but i can't understand your fix about `isprint`.

please separate fix and adding example.

**Comment by moebiussurfing** [comment]
ok @2bbb, without comment:
```
            void keyReleased(ofKeyEventArgs &event) { keyReleased(event.key); }
            std::string print(int key) const {
	        //if(true){
                if(std::isprint(static_cast<char>(key))) {
                    std::string str = "' '";
                    str[1] = static_cast<char>(key);
                    return str;
                } else {
                    return getOfKeyNameFromInt(key);
                }
            }
```
I get this errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0304	no instance of function template "std::isprint" matches the argument list	example_ofxkeyEvent	F:\openFrameworks\addons\ofxKeyEvent\src\ofxKeyEvent.h	147	
Error	C2672	'std::isprint': no matching overloaded function found (compiling source file src\main.cpp)	example_ofxkeyEvent	f:\openframeworks\addons\ofxkeyevent\src\ofxkeyevent.h	147	
Error	C2780	'bool std::isprint(_Elem,const std::locale &)': expects 2 arguments - 1 provided (compiling source file src\main.cpp)	example_ofxkeyEvent	f:\openframeworks\addons\ofxkeyevent\src\ofxkeyevent.h	147	
Error	C2672	'std::isprint': no matching overloaded function found (compiling source file src\ofApp.cpp)	example_ofxkeyEvent	f:\openframeworks\addons\ofxkeyevent\src\ofxkeyevent.h	147	
Error	C2780	'bool std::isprint(_Elem,const std::locale &)': expects 2 arguments - 1 provided (compiling source file src\ofApp.cpp)	example_ofxkeyEvent	f:\openframeworks\addons\ofxkeyevent\src\ofxkeyevent.h	147	

```

should I include some c lib maybe?

I am in OF last version and Visual Studio 2017

**Comment by 2bbb** [comment]
@moebiussurfing 
ah... ok.
maybe it is bug what i didn't include `<cctype>`.
please try to add `#include <cctype>`.

**Comment by 2bbb** [comment]
@moebiussurfing 
maybe i fixed it on current master.
plase check it!!

**Comment by moebiussurfing** [comment]
thanks @2bbb !
yes, now it works. (no need for any modifications.)
I make the 'only example added' pull request now.

**Pull request closed without merging**
